### ISSUE TITLE
Build Create project endpoint

### ISSUE THREAD

**Issue by Richard-outreach** [SeattleVoluntech/seattlevoluntech#59]

**Comment by tara-johnson** [comment]
Added @PostMapping at /projects that saves a project to the projectsRepository

**Comment by Richard-outreach** [comment]
Side note @tara-johnson You'll want to update the project CRUD operations to respect the owner of a project (i.e don't want non-owners to be able to change it). Can do it in a new issue, but just wanted to remind you.
